### ISSUE TITLE
High Sierra compatibility

### ISSUE THREAD

**Issue by dstillman** [zotero/safari-app-extension#3]
https://forums.zotero.org/discussion/comment/344584/#Comment_344584

Hopefully this is just as simple as adjusting some build setting.

**Comment by dstillman** [comment]
Complication: https://forums.zotero.org/discussion/comment/344589#Comment_344589

**Comment by ChaoYan** [comment]
Has this problem fixed?

**Comment by dstillman** [comment]
No, this won't be fixed, sorry. Safari App Extension support in High Sierra was too buggy.
