### ISSUE TITLE
Saving from Amazon is failing

### ISSUE THREAD

**Issue by dstillman** [zotero/safari-app-extension#5]
https://www.amazon.com/dp/0694003611/

D589841783

-1 failures for some of the HTTP requests (URL encoding issue from the ^ and space characters?), followed by absence of save request to app

Reported here: https://forums.zotero.org/discussion/comment/350810/#Comment_350810

**Comment by adomasven** [comment]
Closed with https://github.com/zotero/zotero-connectors/commit/7ef95c6d3648249bd0936a01c977abda5e790589
